### ISSUE TITLE
Latest default circdna version  is 1.0.0 and not 1.0.1

### ISSUE THREAD

**Issue by madagiurgiu25** [nf-core/circdna#34]
### Description of the bug

By default the latest version of circdna is 1.0.0 not 1.0.1. Could you please update the latest version tag?
It might be confusing.
Thank you.

```
nextflow pull nf-core/circdna
Checking nf-core/circdna ...
 done - revision: b0152a3629 [1.0.0]
```

`nextflow.config` contains the version `1.0dev` :

```
manifest {
    name            = 'nf-core/circdna'
    author          = 'Daniel Schreyer'
    homePage        = 'https://github.com/nf-core/circdna'
    description     = 'Pipeline for the identification of circular DNAs'
    mainScript      = 'main.nf'
    nextflowVersion = '!>=21.10.3'
    version         = '1.0dev'
}
```

**Comment by DSchreyer** [comment]
Hi, I cannot replicate the bug. When I perform `nextflow pull nf-core/circdna`, the latest version circdna version 1.0.1 is pulled. However, when version 1.0.0 is pulled, the manifest in the `nextflow.config` gives the confusing version `1.0dev`, which can not be changed. 

When did you pull `nf-core/circdna`? 

My output:
```
nextflow pull nf-core/circdna
Checking nf-core/circdna ...
Fast-forward - revision: 8ff55299f1 [master]
```

**Comment by madagiurgiu25** [comment]
Hi,

I pulled the `nf-core/circdna` on that day, so 24.09.2022.

I pulled now the repository:
```
nextflow pull nf-core/circdna
Checking nf-core/circdna ...
done - revision: 50681adaf7 [1.0.1]

```
