### ISSUE TITLE
Access Denied for Amazon S3 download

### ISSUE THREAD

**Issue by ipstone** [nf-core/circdna#41]
### Description of the bug

I am running circdna with the following command:
`nextflow run nf-core/circdna --input samplesheet_bam.csv --outdir ./output --genome mm10 -profile singularity --circle_identifier ampliconarchitect`

However, we have the following error code:

> Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: M7TW9JYNH1PSHSAH; S3 Extended Request ID: Jy3SRFtmkJqSmeBhMrymGKyYRPU7uxsKFxKeP++PbPUL6B1Qf0dxzbbXicNiQa6AB0EPpKGPQsI=; Proxy: null)

Is there something to be specifically configured (aws s3 access?) to get circdna to run? Thanks

-- Isaac

**Comment by DSchreyer** [comment]
Interesting, this is the first time I see this error. No, normally circdna should be fully runable without aws. Did you find out how this error occured?

**Comment by ipstone** [comment]
Thanks, this error occurs when I am using mm10 as reference - somehow when the reference fasta isn't given, the pipeline tries to download the reference fasta from AWS (for which I don't have access).

I can circumvent this by specifying the reference fasta file such as with:
> --fasta /data/riazlab/projects/_collaborations/Agnel/amplicon_architect/aa_data_repo/mm10/mm10.fa

I guess the setting in 'conf/igenomes.config' specifies where to download the genome, perhaps some configuration can be updated or print out that the pipeline is trying to download a reference genome, when it's not given as a parameter?
