### ISSUE TITLE
reference_build parameter doesn't accept 'mm10' as input

### ISSUE THREAD

**Issue by ipstone** [nf-core/circdna#42]
### Description of the bug

Running the following command:
> nextflow run nf-core/circdna -r 1.0.1 --input samplesheet_bam.csv --outdir ./output --genome mm10 -profile singularity --circle_identifier ampliconarchitect --aa_data_repo ./aa_data_repo --fasta ... --mosek_license_dir ~/.config/mosek --reference_build mm10 

will generate  the error:
> Reference Build not given! Please specify --reference_build 'hg19', 'GRCh38', or 'GRCh37'.

The code checking this condition is at: https://github.com/nf-core/circdna/blob/8ff55299f17693fe25b5221b1c0d93ac08c06b14/workflows/circdna.nf#L51

This condition probably needs to be updated to allow the pipeline to run on mm10 mouse samples. 

Thanks

**Comment by DSchreyer** [comment]
Thanks for bringing this up to me. The AmpliconArchitect branch is not yet updated for mm10, yet. I think it should be easy to do and hope I can do it over the holidays.

**Comment by DSchreyer** [comment]
Hi, I pushed the changes on to `dev`. Would you be willing to pull dev and check if this solved the issue?
