### ISSUE TITLE
No validation of --input_format

### ISSUE THREAD

**Issue by lasseringstedmark** [nf-core/circdna#47]
### Description of the bug

When using circdna with AmpliconArchitect for a already aligned BAM file, i ran into the following problem:

------------------------------------------------------
Access to 'SAMTOOLS_INDEX_BAM.out' is undefined since the process 'SAMTOOLS_INDEX_BAM' has not been invoked before accessing the output attribute

 -- Check script '.nextflow/assets/nf-core/circdna/./workflows/circdna.nf' at line: 302 or see '.nextflow.log' file for more details
------------------------------------------------------

It seems that it is due to --input_format being without capital letters. 

I think it would be nice it if either the --input_format is validated and clearly stated that this should be with capital letters or maybe simply ignore case.

By the way thanks for implementing the tool! :)

**Comment by DSchreyer** [comment]
Hi, thanks for bringing this up to me. I added the parameter check and hope this solves some of the issues.

**Comment by DSchreyer** [comment]
I close this issue. It will be included in the newest udpate and is currently on the dev branch.
