### ISSUE TITLE
Make bam marking duplicates optional when bams are provided

### ISSUE THREAD

**Issue by SPPearce** [nf-core/circdna#49]
### Description of feature

When bam files are provided, the pipeline runs Picard MarkDuplicates, but this may well have already been performed upstream.
For instance, I have bam files with Unique Molecular Identifiers on the reads, which I have already deduplicated in another pipeline, so Picard will mark reads as duplicated even though the UMI says that they come from different unique molecules.

**Comment by DSchreyer** [comment]
This option is already in place and can be activated using the parameter `--skip_markduplicates`. Let me know if this does not work for you.
