### ISSUE TITLE
AmpliconArchitect related paths must be absolute not relative

### ISSUE THREAD

**Issue by SPPearce** [nf-core/circdna#50]
### Description of the bug

The AmpliconArchitect related processes use this structure to set an environment variable:
`export AA_DATA_REPO=${params.aa_data_repo}`
without staging the files in that path into the work directory.
If given an absolute path, this works, but if a relative path is given then the pipeline will fall over with a non-obvious failure message ending in :

`ERROR:root:#TIME 1679058301.012        interval_list: Unable to open interval file "data_repo/GRCh38/".
  Traceback (most recent call last):
    File "~/.nextflow/assets/nf-core/circdna/bin/amplified_intervals.py", line 154, in <module>
      bamFileb2b = b2b.bam_to_breakpoint(bamFile, coverage_stats=cstats)
    File "~/.nextflow/assets/nf-core/circdna/bin/bam_to_breakpoint.py", line 129, in __init__
      self.median_coverage(window_list=coverage_windows)
    File "~/.nextflow/assets/nf-core/circdna/bin/bam_to_breakpoint.py", line 540, in median_coverage
      coverage_stats_file = open(hg.DATA_REPO + "/coverage.stats", "a")
  IOError: [Errno 2] No such file or directory: 'data_repo/coverage.stats'`

I see several ways to fix this:

- Ensure that an absolute path is provided, and fail otherwise.
- Convert the relative path to an absolute path.
- Pass the folder into the folder to stage it (this would be my preferred solution, and possibly is required for other cases than just giving a relative path rather than an absolute one).

**Comment by DSchreyer** [comment]
Thanks for bringing this to my attention. I will note this down in the documentation and when running ampliconarchitect.

**Comment by DSchreyer** [comment]
Included in the newest release
