### ISSUE TITLE
ERROR ~ Argument of `file` function cannot be null

### ISSUE THREAD

**Issue by tjbencomo** [nf-core/circdna#60]
### Description of the bug

Hi - first time nextflow and circdna user. I am trying to run circdna on a tumor BAM file that has already been processed. I followed the instructions in the README and encountered the error in the title. 

I have tested the pipeline using the `-profile test_AA,singularity` flag and it completed without issue.

The only thing I could find on google suggested this might be a nextflow version issue, but my nextflow is up to date. I am running the pipeline from a conda environment that was created for nextflow.

Thanks in advance for the help, and apologies if this is a trivial fix!

### Command used and terminal output

```console
nextflow run nf-core/circdna --input samplesheet.csv --outdir results --genome GRCh38 -profile singularity --circle_identifier ampliconarchitect
N E X T F L O W  ~  version 23.04.1
Launching `https://github.com/nf-core/circdna` [nice_brown] DSL2 - revision: 09a5015cf8 [master]


------------------------------------------------------
                                        ,--./,-.
        ___     __   __   __   ___     /,-._.--~'
  |\ | |__  __ /  ` /  \ |__) |__         }  {
  | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                        `._,._,'
  nf-core/circdna v1.0.4-g09a5015
------------------------------------------------------
Core Nextflow options
  revision         : master
  runName          : nice_brown
  containerEngine  : singularity
  launchDir        : /scratch/users/tbencomo/aus-wgs
  workDir          : /scratch/users/tbencomo/aus-wgs/work
  projectDir       : /home/users/tbencomo/.nextflow/assets/nf-core/circdna
  userName         : tbencomo
  profile          : singularity
  configFiles      : /home/users/tbencomo/.nextflow/assets/nf-core/circdna/nextflow.config

Input/output options
  input            : samplesheet.csv
  outdir           : results

Reference genome options
  genome           : GRCh38
  fasta            : s3://ngi-igenomes/igenomes/Homo_sapiens/NCBI/GRCh38/Sequence/WholeGenomeFasta/genome.fa

Circular DNA identifier options
  circle_identifier: ampliconarchitect

ampliconarchitect options
  reference_build  : null

!! Only displaying parameters that differ from the pipeline defaults !!
------------------------------------------------------
If you use nf-core/circdna for your analysis please cite:

* The pipeline
  https://doi.org/10.5281/zenodo.7712010

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x

* Software dependencies
  https://github.com/nf-core/circdna/blob/master/CITATIONS.md
------------------------------------------------------
ERROR ~ Argument of `file` function cannot be null

 -- Check script '/home/users/tbencomo/.nextflow/assets/nf-core/circdna/./workflows/circdna.nf' at line: 57 or see '.nextflow.log' file for more details
```

### Relevant files

Jul-24 21:54:57.292 [main] DEBUG nextflow.cli.Launcher - $> nextflow run nf-core/circdna --input samplesheet.csv --outdir results --genome GRCh38 -profile singularity --circle_identifier ampliconarchitect
Jul-24 21:54:57.481 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 23.04.1
Jul-24 21:54:57.515 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; embedded=false; plugins-dir=/home/users/tbencomo/.nextflow/plugins; core-plugins: nf-amazon@1.16.2,nf-azure@1.0.1,nf-codecommit@0.1.4,nf-console@1.0.5,nf-ga4gh@1.0.5,nf-google@1.7.3,nf-tower@1.5.12,nf-wave@0.8.2
Jul-24 21:54:57.541 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Jul-24 21:54:57.543 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Jul-24 21:54:57.545 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Jul-24 21:54:57.580 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Jul-24 21:54:57.596 [main] DEBUG nextflow.scm.ProviderConfig - Using SCM config path: /home/users/tbencomo/.nextflow/scm
Jul-24 21:54:59.826 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/users/tbencomo/.nextflow/assets/nf-core/circdna/.git/config; branch: master; remote: origin; url: https://github.com/nf-core/circdna.git
Jul-24 21:54:59.855 [main] DEBUG nextflow.scm.RepositoryFactory - Found Git repository result: [RepositoryFactory]
Jul-24 21:54:59.885 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/users/tbencomo/.nextflow/assets/nf-core/circdna/.git/config; branch: master; remote: origin; url: https://github.com/nf-core/circdna.git
Jul-24 21:55:01.106 [main] DEBUG nextflow.config.ConfigBuilder - Found config base: /home/users/tbencomo/.nextflow/assets/nf-core/circdna/nextflow.config
Jul-24 21:55:01.127 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/users/tbencomo/.nextflow/assets/nf-core/circdna/nextflow.config
Jul-24 21:55:01.160 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `singularity`
Jul-24 21:55:03.593 [main] DEBUG nextflow.config.ConfigBuilder - Available config profiles: [cfc_dev, ifb_core, denbi_qbic, alice, mjolnir_globe, uppmax, incliva, uge, rosalind_uge, lugh, unibe_ibu, vai, czbiohub_aws, jax, ccga_med, scw, tigem, tubingen_apg, google, ipop_up, googlels, eddie, medair, biowulf, apptainer, bi, bigpurple, sbc_sharc, adcra, cedars, vsc_kul_uhasselt, pawsey_nimbus, ucl_myriad, utd_ganymede, charliecloud, icr_davros, ceres, munin, arm, rosalind, hasta, cfc, uzh, ebi_codon_slurm, ebc, ku_sund_dangpu, ccga_dx, crick, marvin, biohpc_gen, shifter, mana, mamba, wehi, awsbatch, imperial, maestro, genotoul, abims, janelia, nu_genomics, googlebatch, oist, sahmri, mpcdf, leicester, vsc_ugent, sage, cambridge, podman, ebi_codon, cheaha, xanadu, test, computerome, seg_globe, sanger, dkfz, pasteur, test_full, azurebatch, hki, crukmi, docker, engaging, gis, hypatia, psmn, eva, fgcz, conda, crg, singularity, test_AA, uw_hyak_pedslabs, prince, utd_sysbio, debug, genouest, cbe, phoenix, gitpod, seawulf, fub_curta, uct_hpc, aws_tower, binac]
Jul-24 21:55:03.701 [main] DEBUG nextflow.cli.CmdRun - Applied DSL=2 from script declararion
Jul-24 21:55:03.701 [main] INFO  nextflow.cli.CmdRun - Launching `https://github.com/nf-core/circdna` [nice_brown] DSL2 - revision: 09a5015cf8 [master]
Jul-24 21:55:03.703 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[]
Jul-24 21:55:03.703 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins resolved requirement=[]
Jul-24 21:55:03.705 [main] DEBUG nextflow.secret.LocalSecretsProvider - Secrets store: /home/users/tbencomo/.nextflow/secrets/store.json
Jul-24 21:55:03.708 [main] DEBUG nextflow.secret.SecretsLoader - Discovered secrets providers: [nextflow.secret.LocalSecretsProvider@3005623b] - activable => nextflow.secret.LocalSecretsProvider@3005623b
Jul-24 21:55:03.819 [main] DEBUG nextflow.Session - Session UUID: f51fdcac-7cc0-43d7-beb2-a0adec6639e2
Jul-24 21:55:03.819 [main] DEBUG nextflow.Session - Run name: nice_brown
Jul-24 21:55:03.820 [main] DEBUG nextflow.Session - Executor pool size: 2
Jul-24 21:55:03.830 [main] DEBUG nextflow.util.ThreadPoolBuilder - Creating thread pool 'FileTransfer' minSize=10; maxSize=10; workQueue=LinkedBlockingQueue[10000]; allowCoreThreadTimeout=false
Jul-24 21:55:03.893 [main] DEBUG nextflow.cli.CmdRun -
  Version: 23.04.1 build 5866
  Created: 15-04-2023 06:51 UTC (14-04-2023 23:51 PDT)
  System: Linux 3.10.0-1160.92.1.el7.x86_64
  Runtime: Groovy 3.0.16 on OpenJDK 64-Bit Server VM 11.0.13+7-b1751.21
  Encoding: UTF-8 (UTF-8)
  Process: 24226@sh02-01n57.int [10.18.1.57]
  CPUs: 1 - Mem: 4 GB (811.9 MB) - Swap: 0 (0)
Jul-24 21:55:03.952 [main] DEBUG nextflow.Session - Work-dir: /scratch/users/tbencomo/aus-wgs/work [lustre]
Jul-24 21:55:03.987 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[]
Jul-24 21:55:04.023 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Jul-24 21:55:04.183 [main] DEBUG nextflow.cache.CacheFactory - Using Nextflow cache factory: nextflow.cache.DefaultCacheFactory
Jul-24 21:55:04.205 [main] DEBUG nextflow.util.CustomThreadPool - Creating default thread pool > poolSize: 2; maxThreads: 1000
Jul-24 21:55:04.405 [main] DEBUG nextflow.Session - Session start
Jul-24 21:55:04.410 [main] DEBUG nextflow.trace.TraceFileObserver - Workflow started -- trace file: /scratch/users/tbencomo/aus-wgs/results/pipeline_info/execution_trace_2023-07-24_21-55-02.txt
Jul-24 21:55:04.444 [main] DEBUG nextflow.Session - Using default localLib path: /home/users/tbencomo/.nextflow/assets/nf-core/circdna/lib
Jul-24 21:55:04.449 [main] DEBUG nextflow.Session - Adding to the classpath library: /home/users/tbencomo/.nextflow/assets/nf-core/circdna/lib
Jul-24 21:55:04.450 [main] DEBUG nextflow.Session - Adding to the classpath library: /home/users/tbencomo/.nextflow/assets/nf-core/circdna/lib/nfcore_external_java_deps.jar
Jul-24 21:55:06.587 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Jul-24 21:55:06.659 [main] INFO  nextflow.Nextflow -

------------------------------------------------------
                                        ,--./,-.
        ___     __   __   __   ___     /,-._.--~'
  |\ | |__  __ /  ` /  \ |__) |__         }  {
  | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                        `._,._,'
  nf-core/circdna v1.0.4-g09a5015
------------------------------------------------------
Core Nextflow options
  revision         : master
  runName          : nice_brown
  containerEngine  : singularity
  launchDir        : /scratch/users/tbencomo/aus-wgs
  workDir          : /scratch/users/tbencomo/aus-wgs/work
  projectDir       : /home/users/tbencomo/.nextflow/assets/nf-core/circdna
  userName         : tbencomo
  profile          : singularity
  configFiles      : /home/users/tbencomo/.nextflow/assets/nf-core/circdna/nextflow.config

Input/output options
  input            : samplesheet.csv
  outdir           : results

Reference genome options
  genome           : GRCh38
  fasta            : s3://ngi-igenomes/igenomes/Homo_sapiens/NCBI/GRCh38/Sequence/WholeGenomeFasta/genome.fa

Circular DNA identifier options
  circle_identifier: ampliconarchitect

ampliconarchitect options
  reference_build  : null

!! Only displaying parameters that differ from the pipeline defaults !!
------------------------------------------------------
If you use nf-core/circdna for your analysis please cite:

* The pipeline
  https://doi.org/10.5281/zenodo.7712010

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x

* Software dependencies
  https://github.com/nf-core/circdna/blob/master/CITATIONS.md
------------------------------------------------------
Jul-24 21:55:08.408 [main] DEBUG nextflow.plugin.PluginUpdater - Installing plugin nf-amazon version: 1.16.2
Jul-24 21:55:08.469 [main] INFO  org.pf4j.AbstractPluginManager - Plugin 'nf-amazon@1.16.2' resolved
Jul-24 21:55:08.469 [main] INFO  org.pf4j.AbstractPluginManager - Start plugin 'nf-amazon@1.16.2'
Jul-24 21:55:08.509 [main] DEBUG nextflow.plugin.BasePlugin - Plugin started nf-amazon@1.16.2
Jul-24 21:55:08.547 [main] DEBUG nextflow.file.FileHelper - > Added 'S3FileSystemProvider' to list of installed providers [s3]
Jul-24 21:55:08.547 [main] DEBUG nextflow.file.FileHelper - Started plugin 'nf-amazon' required to handle file: s3://ngi-igenomes/igenomes/Homo_sapiens/NCBI/GRCh38/Sequence/WholeGenomeFasta/genome.fa
Jul-24 21:55:08.562 [main] DEBUG nextflow.file.FileHelper - Creating a file system instance for provider: S3FileSystemProvider
Jul-24 21:55:08.569 [main] DEBUG nextflow.Global - Using AWS credential defined in `default` section in file: /home/users/tbencomo/.aws/credentials
Jul-24 21:55:08.572 [main] DEBUG nextflow.file.FileHelper - AWS S3 config details: {secret_key=4F+oMa.., region=us-east-1, max_error_retry=5, access_key=AKIAR6..}
Jul-24 21:55:09.251 [main] DEBUG com.upplication.s3fs.AmazonS3Client - Setting S3 glacierRetrievalTier=null
Jul-24 21:55:11.333 [main] DEBUG nextflow.Session - Session aborted -- Cause: Argument of `file` function cannot be null
Jul-24 21:55:11.372 [main] DEBUG nextflow.Session - The following nodes are still active:
  [operator] map
  [operator] collect

Jul-24 21:55:11.389 [main] ERROR nextflow.cli.Launcher - Argument of `file` function cannot be null
java.lang.IllegalArgumentException: Argument of `file` function cannot be null
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:72)
	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:59)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
	at nextflow.Nextflow.file(Nextflow.groovy:99)
	at nextflow.Nextflow.file(Nextflow.groovy)
	at nextflow.Nextflow$file$0.callStatic(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:217)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:231)
	at Script_61043458.runScript(Script_61043458:57)
	at nextflow.script.BaseScript.run0(BaseScript.groovy:145)
	at nextflow.script.BaseScript.run(BaseScript.groovy:192)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:229)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:215)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:205)
	at nextflow.script.IncludeDef.memoizedMethodPriv$loadModule0PathMapSession(IncludeDef.groovy:151)
	at nextflow.script.IncludeDef.access$0(IncludeDef.groovy)
	at nextflow.script.IncludeDef$__clinit__closure2.doCall(IncludeDef.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at org.codehaus.groovy.runtime.memoize.Memoize$MemoizeFunction.lambda$call$0(Memoize.java:137)
	at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:137)
	at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:113)
	at org.codehaus.groovy.runtime.memoize.Memoize$MemoizeFunction.call(Memoize.java:136)
	at nextflow.script.IncludeDef.loadModule0(IncludeDef.groovy)
	at nextflow.script.IncludeDef.load0(IncludeDef.groovy:123)
	at nextflow.script.IncludeDef$load0$1.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at Script_dc663737.runScript(Script_dc663737:36)
	at nextflow.script.BaseScript.run0(BaseScript.groovy:145)
	at nextflow.script.BaseScript.run(BaseScript.groovy:192)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:229)
	at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:224)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:130)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:368)
	at nextflow.cli.Launcher.run(Launcher.groovy:494)
	at nextflow.cli.Launcher.main(Launcher.groovy:653)

### System information

Nextflow: 23.04.1
Hardware: HPC
Executor: Local
Container: Singularity
OS: Cent OS Linux
Version:  v1.0.4-g09a5015

**Comment by DSchreyer** [comment]
Thanks for bringing this to my attention. 
You need to specify the parameters `mosek_license_dir`. Where your mosek license called `mosek.lic` is located. It is questioned on line 57 in the script:  https://github.com/nf-core/circdna/blob/master/workflows/circdna.nf

I also see that you need to specify the `reference_build` using `--reference_build "GRCh38"`. This is important so ampliconarchitect uses the correct reference from the data repository.

I thought I implemented a parameter check for `mosek_license_dir` but it seems to not work. I will include that in the next udpate. Let me know if this fixes it.

**Comment by DSchreyer** [comment]
I updated the circdna.nf script now and it should be implemented in the next update throwing an error when the parameter is not specified.

**Comment by tjbencomo** [comment]
Thank you for addressing this and helping out a nextflow beginner!
