### ISSUE TITLE
make --input_format a required argument when running local command line

### ISSUE THREAD

**Issue by jluebeck** [nf-core/circdna#65]
### Description of feature

I ran
`nextflow run nf-core/circdna -r dev --input colo320dm_samplesheet.csv --outdir colo320dmlc_nftest --genome GRCh38 -profile docker --circle_identifier ampliconarchitect --mosek_license_dir $HOME/mosek --aa_data_repo $AA_DATA_REPO --reference_build GRCh38 --fasta $AA_DATA_REPO/GRCh38/GCA_000001405.15_GRCh38_no_alt_analysis_set.fa`

on my local machine, however the module assumed by default an `--input_format FASTQ` when my samplesheet.csv was 
```
sample,bam
COLO320DM_LC,/home/jens/Desktop/research/bams/COLO320DM_Hung2021.bam
```
and the pipeline crashed in a way that wasn't exactly clear why until I re-visited the web-form and saw that --input_format was a required field on the web form. Can we update so that --input_format is either required on the command-line or deduced from the samplesheet?

Thanks!
Jens

**Comment by DSchreyer** [comment]
Thanks for reporting! Yeah, I agree. I will include that in v1.1
